# Generated by Django 5.0.4 on 2026-05-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='banner_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='hover_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
